import { Inter } from "next/font/google";
import { Caveat } from "next/font/google";
import "@/styles/globals.scss";
import favicon from "./images/favicon.ico";
import faviconPng32 from "./images/favicon-32x32.png";
import faviconPng16 from "./images/favicon-16x16.png";
import androidChrome192 from "./images/android-chrome-192x192.png";
import androidChrome512 from "./images/android-chrome-512x512.png";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
});

const caveat = Caveat({
  subsets: ["latin"],
  weights: [400],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hr">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href={favicon} />
        <link rel="stylesheet" href={inter.url} />
        <link rel="stylesheet" href={caveat.url} />
        <link rel="apple-touch-icon" href={faviconPng32} />
        <link rel="icon" type="image/png" sizes="32x32" href={faviconPng32} />
        <link rel="icon" type="image/png" sizes="16x16" href={faviconPng16} />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href={androidChrome192}
        />
        <link
          rel="icon"
          type="image/png"
          sizes="512x512"
          href={androidChrome512}
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-title" content="Create Next App" />
        <meta name="application-name" content="Create Next App" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="msapplication-config" content="/browserconfig.xml" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
