import { Inter } from "next/font/google";
import { Caveat } from "next/font/google";
import "@/styles/globals.scss";
import favicon from "@/public/favicon.ico";

import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
});

const caveat = Caveat({
  subsets: ["latin"],
  weights: [400],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, React, Tailwind CSS",
  favicon: favicon,
};

export default function RootLayout({ children }) {
  return (
    <html lang="hr">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
