import { Inter } from "next/font/google";
import { Caveat } from "next/font/google";
import "@/styles/globals.scss";

import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
});

const caveat = Caveat({
  subsets: ["latin"],
  weights: [400],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hr">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
        <link rel="mask-icon" href="%PUBLIC_URL%/logo.svg" color="#000000" />
        <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
        <meta name="apple-mobile-web-app-title" content="Create Next App" />
        <meta name="application-name" content="Create Next App" />
        <link rel="manifest" href="%PUBLIC_URL%/site.webmanifest" />
        <link rel="manifest" href="%PUBLIC_URL%/site.webmanifest" />
        <link
          rel="mask-icon"
          href="%PUBLIC_URL%/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
        <meta name="apple-mobile-web-app-title" content="Create Next App" />
        <meta name="application-name" content="Create Next App" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta
          name="msapplication-config"
          content="%PUBLIC_URL%/browserconfig.xml"
        />
        <meta name="theme-color" content="#ffffff" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
